-- Basic schema for Skillnora

-- users
create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  email text unique,
  full_name text,
  role text default 'student', -- student, instructor, admin
  activity_heatmap jsonb default '{}'::jsonb, -- stores watch dates for heatmap
  created_at timestamptz default now()
);

-- courses
create table if not exists courses (
  id uuid primary key default gen_random_uuid(),
  instructor_id uuid references users(id),
  title text,
  slug text unique,
  description text,
  thumbnail_url text,
  category text,
  target_role text,
  primary_skill text,
  certificate_type text,
  price numeric default 0,
  discount_price numeric,
  is_published boolean default false,
  average_rating numeric(3,2) default null, -- e.g. 4.50
  total_reviews integer default 0,
  attachments jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- lectures (modules)
create table if not exists lectures (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references courses(id) on delete cascade,
  title text,
  video_url text,
  thumbnail_url text,
  position integer,
  mcqs jsonb default '[]'::jsonb, -- MCQ quiz questions for this module
  created_at timestamptz default now()
);

-- enrollments
create table if not exists enrollments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id),
  course_id uuid references courses(id),
  enrolled_at timestamptz default now(),
  expires_at timestamptz, -- if null, it's lifetime access
  progress jsonb default '{}'::jsonb
);

-- certificates
create table if not exists certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id),
  course_id uuid references courses(id),
  issued_at timestamptz default now(),
  verification_code text unique
);

-- orders (payments)
create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  razorpay_order_id text unique,
  user_id uuid references users(id),
  course_id uuid references courses(id),
  amount numeric,
  currency text default 'INR',
  status text default 'created', -- created, paid, failed
  receipt text,
  created_at timestamptz default now()
);

-- reviews
create table if not exists reviews (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references courses(id) on delete cascade,
  user_id uuid references users(id) on delete cascade,
  rating integer check (rating >= 1 and rating <= 5),
  review_text text, -- optional written review
  created_at timestamptz default now(),
  unique(course_id, user_id) -- one review per user per course
);

create or replace function update_course_rating()
returns trigger as $$
begin
  update courses
  set 
    total_reviews = (select count(*) from reviews where course_id = coalesce(new.course_id, old.course_id)),
    average_rating = (select avg(rating)::numeric(3,2) from reviews where course_id = coalesce(new.course_id, old.course_id))
  where id = coalesce(new.course_id, old.course_id);
  
  return null;
end;
$$ language plpgsql;

drop trigger if exists trg_update_course_rating on reviews;
create trigger trg_update_course_rating
after insert or update or delete on reviews
for each row execute function update_course_rating();

-- Missing Tables Additions
create table if not exists wishlist_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  course_id uuid references courses(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, course_id)
);

create table if not exists notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  course_id uuid references courses(id) on delete cascade,
  lecture_id text,
  text text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id) on delete cascade,
  type text,
  message text,
  is_read boolean default false,
  link text,
  created_at timestamptz default now()
);

-- refunds
create table if not exists refunds (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id),
  course_id uuid references courses(id),
  amount numeric,
  reason text,
  status text default 'processed',
  created_at timestamptz default now()
);

-- lecture_comments (for Q&A threads)
create table if not exists lecture_comments (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  course_slug text not null,
  lecture_id text not null,
  user_id uuid references auth.users(id),
  user_name text not null,
  role text not null,
  text text,
  image_url text,
  parent_id bigint references lecture_comments(id) on delete cascade
);

-- Policies for lecture_comments
alter table lecture_comments enable row level security;
drop policy if exists "Anyone can read comments" on lecture_comments; create policy "Anyone can read comments" on lecture_comments for select using (true);
drop policy if exists "Authenticated users can insert comments" on lecture_comments; create policy "Authenticated users can insert comments" on lecture_comments for insert with check (auth.uid() = user_id);
drop policy if exists "Users can delete own comments" on lecture_comments; create policy "Users can delete own comments" on lecture_comments for delete using (auth.uid() = user_id);

-- support_tickets
create table if not exists support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references users(id),
  name text,
  email text,
  subject text,
  message text,
  priority text default 'Medium',
  status text default 'Open',
  created_at timestamptz default now()
);
-- Example Row-Level Security (RLS) policies for Skillnora

-- Enable RLS on key tables
alter table if exists users enable row level security;
alter table if exists courses enable row level security;
alter table if exists lectures enable row level security;
alter table if exists enrollments enable row level security;

-- Allow users to read their own user row
drop policy if exists select_own_user on users;
create policy select_own_user on users
  for select using (auth.uid() = id);

-- Allow users to insert their own profile (on signup flows handled server-side)
drop policy if exists insert_user on users;
create policy insert_user on users
  for insert with check (auth.uid() = id);

-- Allow instructors to manage (insert/update/delete) their own courses
drop policy if exists instructor_manage_course on courses;
create policy instructor_manage_course on courses
  for all using (auth.uid() = instructor_id) with check (auth.uid() = instructor_id);

-- Allow read of published courses by anyone, and private by instructor/admin
drop policy if exists public_read_published_courses on courses;
create policy public_read_published_courses on courses
  for select using (is_published = true or auth.uid() = instructor_id);

-- Allow enrolled users to read lectures of a course
drop policy if exists enrolled_read_lectures on lectures;
create policy enrolled_read_lectures on lectures
  for select using (
    exists (select 1 from enrollments e where e.user_id = auth.uid() and e.course_id = lectures.course_id)
    or exists (select 1 from courses c where c.id = lectures.course_id and c.is_published)
  );

-- Admin role checks (requires role claim mapping in JWT or user metadata)
-- Example: allow if the jwt.claims.role = 'admin'
-- create policy admin_all on courses for all using (auth.jwt() ->> 'role' = 'admin');

-- Orders policies: allow users to see their own orders, and allow inserts only via service role (server)
alter table if exists orders enable row level security;
drop policy if exists select_own_orders on orders;
create policy select_own_orders on orders
  for select using (auth.uid() = user_id);
drop policy if exists insert_orders_server on orders;
create policy insert_orders_server on orders
  for insert with check (auth.role() = 'authenticated' or true);

